name: "Deploy to Kubernetes"
description: "Create or update kubernetes deployment using docker image"
inputs:
  kubeConfig:
    description: "kubernetes config encoded with base64"
    required: true
  name:
    description: "kubernetes deployment name"
    required: true
  image:
    description: "docker image to deploy"
    required: true
  namespace:
    description: "kubernetes namespace"
    required: false
    default: "default"
  imagePullSecrets:
    description: "kubernetes image pull secrets"
    required: false
    default: "hub"
runs:
  using: "composite"
  steps:
    - name: "Setup"
      shell: bash
      run: |
        echo "APP_NAME=${{ inputs.name }}" >> $GITHUB_ENV
        echo "IMAGE=${{ inputs.image }}" >> $GITHUB_ENV
        echo "NAMESPACE=${{ inputs.namespace }}" >> $GITHUB_ENV
        echo "IMAGE_PULL_SECRETS=${{ inputs.imagePullSecrets }}" >> $GITHUB_ENV
        echo "KUBECONFIG=${{ inputs.kubeConfig }} | base64 -d" >> $GITHUB_ENV
    - name: "Deploy to kubernetes"
      shell: bash
      run: start.sh
